//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduCampus
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.GridView gvAssignedCourses;

        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;

        protected global::System.Web.UI.WebControls.GridView gvPoorAttendance;

        protected global::System.Web.UI.DataVisualization.Charting.Chart chartGrades;

        protected global::System.Web.UI.WebControls.Button btnLogout;
    }
}