using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.Text;

namespace EduCampus
{
    public partial class RegisterLecturer : System.Web.UI.Page
    {
        string connStr = ConfigurationManager.ConnectionStrings["EduCampusDB"].ConnectionString;
        protected void Page_Load(object sender, EventArgs e)
        {
            // Protect page (must login first)
            if (Session["Role"] == null)
            {
                Response.Redirect("Login.aspx");
                return;
            }

            if (Session["Role"].ToString() != "Admin")
            {
                Response.Redirect("AccessDenied.aspx");
                return;
            }

            if (!IsPostBack)
            {
                LoadLecturers();
            }
        }

        // Hashes the password using SHA-256 before storing it in the database
        private string HashPassword(string password)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] bytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));

                StringBuilder builder = new StringBuilder();

                foreach (byte b in bytes)
                {
                    builder.Append(b.ToString("x2"));
                }

                return builder.ToString();
            }
        }

        // Loads all registered lecturers into the GridView
        private void LoadLecturers()
        {
            using (SqlConnection conn = new SqlConnection(connStr))
            {
                // Join Lecturers and Users tables to retrieve lecturer details
                string query = @"
                    SELECT 
                        l.LecturerID, 
                        u.FullName, 
                        u.Email, 
                        l.Department  
                    FROM Lecturers l  
                    INNER JOIN Users u 
                        ON l.UserID = u.UserID";

                SqlDataAdapter da = new SqlDataAdapter(query, conn);
                DataTable dt = new DataTable();
                da.Fill(dt);

                gvLecturers.DataSource = dt;
                gvLecturers.DataBind();
            }
        }

        protected void btnRegister_Click(object sender, EventArgs e)
        {
            // Validate that all required fields have been filled in
            if (txtName.Text == "" || txtLecturerEmail.Text == "" || txtLecturerPass.Text == "" || txtDept.Text == "")
            {
                lblMessage.CssClass = "text-danger";
                lblMessage.Text = "Please fill in all fields!";
                return;
            }

            // Hash password before saving it to the database
            string hashedPassword = HashPassword(txtLecturerPass.Text);

            using (SqlConnection conn = new SqlConnection(connStr))
            {
                try
                {
                    // Check whether the email already exists
                    string checkQuery = "SELECT COUNT(*) FROM Users WHERE Email = @email";

                    SqlCommand checkCmd = new SqlCommand(checkQuery, conn);
                    checkCmd.Parameters.AddWithValue("@email", txtLecturerEmail.Text);

                    conn.Open();

                    int count = Convert.ToInt32(checkCmd.ExecuteScalar());

                    if (count > 0)
                    {
                        lblMessage.CssClass = "text-danger";
                        lblMessage.Text = "Email already exists. Please use another email.";
                        return;
                    }

                    // Insert lecturer login information into Users table
                    string userQuery = @"
                        INSERT INTO Users (FullName, Email, PasswordHash, Role) 
                        VALUES (@name, @email, @password, 'Lecturer');

                        SELECT SCOPE_IDENTITY();";

                    SqlCommand userCmd = new SqlCommand(userQuery, conn);

                    userCmd.Parameters.AddWithValue("@name", txtName.Text);
                    userCmd.Parameters.AddWithValue("@email", txtLecturerEmail.Text);
                    userCmd.Parameters.AddWithValue("@password", hashedPassword);

                    // Retrieve the UserID generated by SQL Server
                    int userID = Convert.ToInt32(userCmd.ExecuteScalar());

                    // Insert lecturer-specific information into Lecturers table
                    string lecturerQuery = @"
                        INSERT INTO Lecturers (Department, UserID)
                        VALUES (@dept, @userID)";

                    SqlCommand lecturerCmd = new SqlCommand(lecturerQuery, conn);
                    
                    lecturerCmd.Parameters.AddWithValue("@dept", txtDept.Text);
                    lecturerCmd.Parameters.AddWithValue("@userID", userID);

                    lecturerCmd.ExecuteNonQuery();

                    lblMessage.CssClass = "text-success";
                    lblMessage.Text = "Lecturer registered successfully!";

                    // Clear form fields after successful registration
                    txtName.Text = "";
                    txtLecturerEmail.Text = "";
                    txtLecturerPass.Text = "";
                    txtDept.Text = "";

                    // Refresh lecturer list
                    LoadLecturers(); 
                }
                catch (Exception ex)
                {
                    lblMessage.CssClass = "text-danger";
                    lblMessage.Text = "Error: " + ex.Message;
                }
            }
        }

        protected void btnSearch_Click(object sender, EventArgs e)
        {
            using (SqlConnection conn = new SqlConnection(connStr))
            {
                // Search lecturers by department
                string query = @"
                    SELECT
                        l.LecturerID,
                        u.FullName,
                        u.Email,
                        l.Department
                    FROM Lecturers l
                    INNER JOIN Users u
                        ON l.UserID = u.UserID
                    WHERE l.Department LIKE @dept";

                SqlCommand cmd = new SqlCommand(query, conn);
                cmd.Parameters.AddWithValue("@dept", "%" + txtSearchDept.Text + "%");

                SqlDataAdapter da = new SqlDataAdapter(cmd);
                DataTable dt = new DataTable();
                da.Fill(dt);

                gvLecturers.DataSource = dt;
                gvLecturers.DataBind();
            }
        }

        protected void btnReset_Click(object sender, EventArgs e)
        {
            txtSearchDept.Text = "";
            LoadLecturers();
        }

        // Logout
        protected void btnLogout_Click(object sender, EventArgs e)
        {
            Session.Clear();              // clear session
            Response.Redirect("Login.aspx"); // go back to login
        }
    }
}